#!/bin/sh
# Creates a virtual machine

NAME=''
OSTYPE='ArchLinux_64'
MEMORY='8196'
HDD='70000'

usage() {
 echo "Usage: VBoxCreate name --ostype ostype --hdd sizeGiB --memory sizeMiB "
 echo "    ostype: ArchLinux_64 default"
 exit 1
}

# ':' - argument is required
# '::' - argument is optional
# --name is a name ofthe this script
get_options() {
  opts=$(getopt --longoptions "ostype:,hdd:,memory:" --name "VBoxCreate" --options "" -- "$@")
  if [ "$?" -ne 0 ]; then
      usage
  fi
  eval set -- "$opts"

  while true; do
     arg=$2
     if [ "$1" != '--' -a "${arg:0:2}" == '--' ]; then
        echo "Option $1 should have a value"
        usage
     fi
     case "$1" in
        --ostype) OSTYPE=$2 ; shift 2 ;;
        --hdd) HDD=$2 ; shift 2 ;;
        --memory) MEMORY=$2 ; shift 2 ;;
        --) shift ; break ;;
        *) echo 'Unexpected' ; shift ;;
     esac
  done

  if [ "$#" -lt 1 ]; then
     echo "Name should be provided"
     usage
  fi
  NAME=$1
}

get_options $@
echo "About to create virtual machine $NAME"
echo "OS type $OSTYPE"
echo "Memory $MEMORY MiB"
echo "HDD $HDD Gib"
echo "Press ENTER to continue"
read

